# Generated by Django 5.2.4 on 2025-07-14 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('daily_capacity', models.PositiveSmallIntegerField(default=8)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='assignments.position')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.PositiveSmallIntegerField()),
                ('date', models.DateField(db_index=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='assignments.position')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('hours', models.PositiveSmallIntegerField()),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='assignments.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assignments.task')),
            ],
            options={
                'indexes': [models.Index(fields=['work_date'], name='assignments_work_da_6a7d9c_idx'), models.Index(fields=['worker', 'work_date'], name='assignments_worker__4d31f7_idx'), models.Index(fields=['task'], name='assignments_task_id_7a321f_idx')],
                'unique_together': {('worker', 'task')},
            },
        ),
    ]
