# Generated by Django 5.2.4 on 2025-07-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='daily_capacity',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
    ]
